const dataFromDB = [
  {
    name: "Windows 10 Home",
    img: "../assets/windows10home.jpg",
    tipo: "Retail",
    duracion: "de por vida",
    precio: "1500",
    stock: 29,
    idCategory: "SistemaOperativo",
    id: 1,
  },
  {
    name: "Windows 11 Home",
    img: "../assets/windows11home.jpg",
    tipo: "OEM",
    duracion: "de por vida",
    precio: "1850",
    stock: 11,
    idCategory: "SistemaOperativo",
    id: 2,
  },
  {
    name: "Office 2021",
    img: "../assets/Office-2021-Professional-Plus.jpg",
    tipo: "Retail",
    duracion: "1 año",
    precio: "2100",
    stock: 11,
    idCategory: "Software",
    id: 3,
  },
  {
    name: "Fifa 22",
    img: "../assets/Office-2021-Professional-Plus.jpg",
    tipo: "PS Key",
    duracion: "de por vida",
    precio: "9000",
    stock: 11,
    idCategory: "Juegos",
    id: 4,
  },
  {
    name: "Horizon Zero Dawn",
    img: "../assets/Office-2021-Professional-Plus.jpg",
    tipo: "Steam Key",
    duracion: "de por vida",
    precio: "4200",
    stock: 11,
    idCategory: "Juegos",
    id: 5,
  },
  {
    name: "CS:GO Prime Status",
    img: "../assets/Office-2021-Professional-Plus.jpg",
    tipo: "DLC",
    duracion: "de por vida",
    precio: "1500",
    stock: 11,
    idCategory: "Juegos",
    id: 6,
  },
];

export default dataFromDB;
